### ISSUE TITLE
Final annotations number does not match reported issues from logs.

### ISSUE THREAD

**Issue by jason-murray** [staabm/annotate-pull-request-from-checkstyle#106]
Hi there, I'm using this to parse a phpcs checkstyle report using:

`bin/phpcs -q --report=checkstyle src | cs2pr --graceful-warnings --notices-as-warnings --prepend-source`

On my PR the action logs note 100's of issues, however the PR is only annotated for 10 errors and 11 warnings. I am rerunning this action to try different things but the checks/annotations number never changes.

When running locally I see a significant number of `::error` and `::warning` lines but these don't all seem to be making it in to the checks tab. Also the annotations that do go in are from a couple of random files in the tree, it's not like the first 10 in the report it just seems to be a few scattered throughout the report.

**Comment by jason-murray** [comment]
Actually I've discovered that GitHub imposes limits on annotations - this is a shame as it makes tooling like this less useful.

However there is the possibility now to apply markdown summaries as annotations which may allow a middle ground.

> 10 warning annotations and 10 error annotations per step
> 50 annotations per job (sum of annotations from all the steps)
> 50 annotations per run (separate from the job annotations, these annotations aren’t created by users

**Comment by staabm** [comment]
I agree that the limited number of annotations is a problem.

in case you have more annotations then the github limit, working thru them most of the time is better handled elsewhere.

we use it mostly as a alarm sign.
