### ISSUE TITLE
Problems with empty check style report

### ISSUE THREAD

**Issue by kevinpapst** [staabm/annotate-pull-request-from-checkstyle#15]
First of all: thanks for your tool!

I am running into an issue while setting up a GitHub action in case `php-cs-fixer` doesn't find any problem. If there is an issue in the code, it is properly annotated and reported in the PR. 

But when running `cs2pr` piped from `php-cs-fixer` on sources that do not report any issue, I [get this message](https://github.com/kevinpapst/kimai2/pull/1452/checks?check_run_id=434673815):

```
  Run php-cs-fixer fix --dry-run --verbose --config=.php_cs.dist --using-cache=no --show-progress=none --format=checkstyle | cs2pr 14s

##[error]Process completed with exit code 2.
Run php-cs-fixer fix --dry-run --verbose --config=.php_cs.dist --using-cache=no --show-progress=none --format=checkstyle | cs2pr
Loaded config default from ".php_cs.dist".
unknown error. expecting checkstyle formatted xml input.
##[error]Process completed with exit code 2.
```

Running `php-cs-fixer` on a clean code base reports:
```
$ php-cs-fixer fix --dry-run --format=checkstyle --config=.php_cs.dist -v --stop-on-violation --using-cache=no
Loaded config default from ".php_cs.dist".
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle/>
```

Running this:
```
$ php -r '$a = simplexml_load_string("<?xml version=\"1.0\" encoding=\"UTF-8\"?><checkstyle/>"); if (!$a) { var_dump($a); $b = libxml_get_errors(); if (!$b) { var_dump($b); } }'
```
leads to:
```
Command line code:1:
class SimpleXMLElement#1 (0) {
}
Command line code:1:
array(0) {
}
```

So I believe your [recent changes here](https://github.com/staabm/annotate-pull-request-from-checkstyle/blob/master/cs2pr#L41) are not catching the case of an empty `<checkstyle/>` block.

**EDIT:** [This test fails](https://github.com/staabm/annotate-pull-request-from-checkstyle/blob/master/tests/tests.php#L46) if you change its content from 
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle>
</checkstyle>
```
to 
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle/>
```

**Comment by staabm** [comment]
Hmm I get the feeling we have a similar problem for psalm :-/

**Comment by kevinpapst** [comment]
Never used Psalm before, only phpstan ... but what do you mean: did this fix introduce another problem?

**Comment by staabm** [comment]
I meant that the changed in 1.0.2 also introduced some errors for psalm, not just for php-cs-fixer.

Example failing build https://github.com/redaxo/redaxo/pull/3286/checks?check_run_id=434867078


Need to investigate

**Comment by staabm** [comment]
I guess I found the psalm problem with https://github.com/vimeo/psalm/issues/2778
