### ISSUE TITLE
Please update the latest release to add cs2pr

### ISSUE THREAD

**Issue by shivammathur** [staabm/annotate-pull-request-from-checkstyle#17]
@staabm Please update the latest release to add cs2pr file

**Comment by staabm** [comment]
Created the latest release on mobile. Will add the asset when back on a real workstation :)

Thx for the headsup though

**Comment by shivammathur** [comment]
@staabm 
Maybe you can automate this using https://github.com/actions/upload-release-asset

**Comment by staabm** [comment]
just added the assets manually. will open a new issue for the automation task
