### ISSUE TITLE
automate release asset upload

### ISSUE THREAD

**Issue by staabm** [staabm/annotate-pull-request-from-checkstyle#22]
`cs2pr` is bundled with https://github.com/shivammathur/setup-php.
for this to work, https://github.com/shivammathur/setup-php needs a "cs2pr" release asset bundled with every release we make.

this asset upload is currently done manually (and therefore sometimes forgotten).

Maybe we can automate this using https://github.com/actions/upload-release-asset ?
(or with any other action?)

triggered by https://github.com/staabm/annotate-pull-request-from-checkstyle/issues/17

**Comment by staabm** [comment]
@localheinz maybe this is something you are willing to look into - when time allows?

**Comment by localheinz** [comment]
@staabm 

Can do!
