### ISSUE TITLE
Create GitHub action

### ISSUE THREAD

**Issue by dkarlovi** [staabm/annotate-pull-request-from-checkstyle#3]
It's much easier to use without installing etc.

**Comment by staabm** [comment]
I just opened a issue on https://github.com/shivammathur/setup-php/issues/161 which discusses to bundle the script with the `shivammathur/setup-php@v1` github action.

I guess this will be used in the majority of use-cases.

would this work for you, too?

or do you plan to use the tool within a different context?

**Comment by dkarlovi** [comment]
I don't use that action since it's just thick CI magic which makes it harder to be reproducible locally.

I prefer to do it with [a prebuilt Docker image](https://github.com/jakzal/phpqa), [a Makefile](https://github.com/dkarlovi/xezilaires/blob/master/Makefile) and [have CI just be "CPU and memory"](https://github.com/dkarlovi/xezilaires/blob/master/.github/workflows/continuous-integration.yaml) running it.

Having this tool be a stand-alone action which would just provide the Checkstyle -> GitHub annotations would be preferable to me.

**Comment by staabm** [comment]
@dkarlovi feel free to provide the necessary setup as a PR to this repo
