### ISSUE TITLE
Add check for <?xml in sdtin input

### ISSUE THREAD

**Issue by prisis** [staabm/annotate-pull-request-from-checkstyle#30]
Hey, maybe my use case is a bit special.

Im have all dev tools in a different folder, and using the `--working-dir` from `composer` to call the tools.

use case: 
```
composer --working-dir=./.build cs:check -- --format=checkstyle
> php-cs-fixer fix --config="./../.php_cs" --dry-run '--format=checkstyle'
Loaded config narrowspark from "./../.php_cs".
Using cache file "/var/www/package/.build/php-cs-fixer/.php_cs.cache".
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle/>
```

error: 
```
Start tag expected, '<' not found
 on line 1, column 1
```

Possible solution is to search for the `<?xml ver..` position and remove everything before this input

**Comment by staabm** [comment]
The php-cs-fixer should output the text Using cache file "/var/www/package/.build/php-cs-fixer/.php_cs.cache". On stderr

**Comment by staabm** [comment]
Hmm just had a lookup of the php-cs-fixer sources and at least the latest master branch outputs this things on stderr. 

Maybe I misunderstood the issue. Which output is passed via stdout to cs2pr?

**Comment by prisis** [comment]
The output from composer script where I call the cs fixer or phpstan, see this work flow as example https://github.com/PrisisForks/php-cs-fixer-config/blob/feature/update-repro/.github/workflows/coding-standard.yml you can check the action tab if you need to see the error

I you want I can create a pr

**Comment by prisis** [comment]
Found the error : 
`Run php -d memory_limit=-1 composer --working-dir=./.build phpstan -- --error-format=checkstyle`

`Could not open input file: composer`

Thank you, @staabm for the help

**Comment by staabm** [comment]
I built a new version which will pass thru this error messages to ease debugging .. next time :-)

**Comment by mirko-pagliai** [comment]
I have the same problem. The test is successful, locally too, but this error occurs. What can it depend on?

**Comment by staabm** [comment]
Could you share a example repo or code which reproduces the problem?

**Comment by mirko-pagliai** [comment]
> Could you share a example repo or code which reproduces the problem?

[Here](https://github.com/mirko-pagliai/php-tools/runs/3723107064?check_suite_focus=true) for example.

```
Run vendor/bin/phpcs -n --report=checkstyle src/ tests/ | cs2pr
  vendor/bin/phpcs -n --report=checkstyle src/ tests/ | cs2pr
  shell: /usr/bin/bash -e {0}
Error: Start tag expected, '<' not found on line 1, column 1

....................................................... 55 / 55 (100%)


<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="3.6.0">
</checkstyle>
Time: 957ms; Memory: 14MB

Error: Process completed with exit code 2.
```

This is [the workflow file](https://github.com/mirko-pagliai/php-tools/actions/runs/1279195522/workflow).

**Comment by staabm** [comment]
are you sure there is no new-line or similar before the `<`?

**Comment by mirko-pagliai** [comment]
> are you sure there is no new-line or similar before the `<?xml`?

Before... what? If I am not mistaken, that is the output generated by phpcs.
There is only the progress bar, and perhaps that gives problems (?).
If so, always take the `-q` option (for phpcs) for granted (?).

**Comment by staabm** [comment]
Yeah, I guess the progress bar might be the problem. 

Does it work with `-q`?
If so, could you update the Readme and add the argument?

**Comment by mirko-pagliai** [comment]
> Yeah, I guess the progress bar might be the problem.
> 
> Does it work with `-q`? If so, could you update the Readme and add the argument?

Actually [the readme](https://github.com/staabm/annotate-pull-request-from-checkstyle#using-php_codesniffer) seems correct to me. I hadn't paid any attention to it.
