### ISSUE TITLE
"Could not setup cs2pr" in shivammathur/setup-php@v1

### ISSUE THREAD

**Issue by Kocal** [staabm/annotate-pull-request-from-checkstyle#35]
Hi,

It looks like the last release [1.0.5](https://github.com/staabm/annotate-pull-request-from-checkstyle/releases/tag/1.0.5) broke shivammathur/setup-php@v1:

![Sélection_999(674)](https://user-images.githubusercontent.com/2103975/74635717-e2189f80-5166-11ea-937b-b0f0fb5083db.png)

We didn't have this issue before.

I've opened an issue in their repo too: https://github.com/shivammathur/setup-php/issues/178

Thanks

**Comment by shivammathur** [comment]
@staabm Please add the file manually to the release until the issue is resolved.

**Comment by staabm** [comment]
just added the artefact. sorry for the trouble.

@Kocal please report back, whether your problem is fixed. will close the PR for now.

**Comment by shivammathur** [comment]
@staabm Works now 👍
