### ISSUE TITLE
Support Phpspec and PHP_Code_Sniffer

### ISSUE THREAD

**Issue by tristanbes** [staabm/annotate-pull-request-from-checkstyle#6]
Hello,

Is there any plans to support PhpSpec + PHP_Code_Sniffer (phpcs) ?

Thanks :)

**Comment by staabm** [comment]
Hi!

actually this tools supports any tool which is able to produce a checkstyle-formatted report.

a quick looks shows that PhpSpec does not support this format, but phpcs already does:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Reports/Checkstyle.php
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-a-checkstyle-report

feel free to open a issue on phpspec and propose the addition of a checkstyle-formatted error report.

**Comment by staabm** [comment]
just added a example for use with PHP_Code_Sniffer in https://github.com/staabm/annotate-pull-request-from-checkstyle/commit/34d27f701b3454e2bfa6834ea43b83198b37c949

**Comment by staabm** [comment]
I will close the issue for now, as there is nothing more I can do here.
phpspec need to provide the error in the correct format.

feel free to discuss further or ask open questions.
