### ISSUE TITLE
::notice does not annotate

### ISSUE THREAD

**Issue by pcrov** [staabm/annotate-pull-request-from-checkstyle#61]
While the Checks API supports notices, [workflow commands](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions) do not. Outputting these does not annotate anything, they're just another line in the action log (and they're not even dressed up there.) Short of using the checks api, you might consider promoting these to warnings, ignoring them completely, or giving the user the option what to do.

If you go the user option route it might be useful to allow them to specify which severities map to which types of annotation. While [valid values for checkstyle's `@severity`](https://checkstyle.sourceforge.io/property_types.html#SeverityLevel) appear to be ignore, info, warning, and error I don't know how well other tools hold to those (the list wasn't super easy to find and doesn't mention the xml format.)

**Comment by staabm** [comment]
Should be covered with https://github.com/staabm/annotate-pull-request-from-checkstyle/pull/69
