### ISSUE TITLE
Filename not shown

### ISSUE THREAD

**Issue by CLL-GTA** [staabm/annotate-pull-request-from-checkstyle#84]
I'm using `cs2pr` with `php-cs-fixer`. I have installed verison 1.7.1  via the `shivammathur/setup-php@v2` action.

![Screenshot 2021-11-03 at 16 52 18](https://user-images.githubusercontent.com/92724269/140108724-9a6de096-ed02-4c51-83ef-bc2e6fe40457.png)

I use the `--dry-run --using-cache=no --format=checkstyle` so that I can just see what is wrong and then I would manually fix it with another commit. However, if something is wrong, I only see the message and not the filename

![Screenshot 2021-11-03 at 16 55 15](https://user-images.githubusercontent.com/92724269/140112365-4a910add-3155-4ccd-a425-c381c0cc4219.png)

The actual XML report is

```xml
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle>
  <file name="CareLineLive/app/Http/Controllers/Exports/CarersExportController.php">
    <error severity="warning" source="PHP-CS-Fixer.no_unused_imports" message="Found violation(s) of type: no_unused_imports"/>
  </file>
</checkstyle>
```

I don't think this is expected behaviour, right?

**Comment by staabm** [comment]
could you provide a failing testcase?

see https://github.com/staabm/annotate-pull-request-from-checkstyle/tree/master/tests

**Comment by CLL-GTA** [comment]
I think maybe the issue is with the `shivammathur/setup-php@v2` action.

I think `cs2pr` correctly returns something like `:warning file=CareLineLive/app/Http/Controllers/Exports/CarersExportController.php::Found violation(s) of type: no_unused_imports.` (i'm not disputing it doesn't).

Therefore I would expect to see the filename as well in the output of the action.

I think I will open an issue over there.
