### ISSUE TITLE
False positive with PHP Cs fixer 2

### ISSUE THREAD

**Issue by vasilvestre** [staabm/annotate-pull-request-from-checkstyle#85]
Hello,

Running `vendor/bin/php-cs-fixer fix --dry-run --format=xml | cs2pr` return error code 1.
Here's the output :

```
Loaded config default from "/home/ubuntu/projects/perso/multistream-tools/.php-cs-fixer.dist.php".
Using cache file ".php-cs-fixer.cache".
::warning file=,line=::
```

**Comment by staabm** [comment]
You need to use a different format, see the readme.

`php-cs-fixer fix --dry-run --format=checkstyle | cs2pr`

**Comment by vasilvestre** [comment]
> You need to use a different format, see the readme.
> 
> `php-cs-fixer fix --dry-run --format=checkstyle | cs2pr`

I see you are quite polite so I will tell it myself.. RTFM :D
