### ISSUE TITLE
Is it possible to support Gitlab Merge Request?

### ISSUE THREAD

**Issue by LuChenjing** [staabm/annotate-pull-request-from-checkstyle#94]
Just like github action, gitlab ci may contains lots of stages with different lint check. Is there any tools can be used to annotate the MR from CI lint just like `cs2pr`?

**Comment by staabm** [comment]
hi,

I never used gitlab. does gitlab has a annotation format like the github pull requests?

**Comment by LuChenjing** [comment]
Hi, is the annotation format you mentioned just like adding a comment into the change file?
I wish could find a common tool to add the incorrect lint result to the file lines using like `cs2pr`.
Or may be we have to analysis the different result of all the lints, then call the `notes API` of MR..

**Comment by staabm** [comment]
Cs2pr atm just turns errors formatted in the checkstyle-format into another format, which github pull requests natively understood and mark in pull requests.

Not sure there is a similar format gitlab understands.

**Comment by staabm** [comment]
Feel free to ask fuether questions.. closing for now
